### ISSUE TITLE
 the preprocessing steps applied to the NYU-Depth dataset

### ISSUE THREAD

**Issue by hamlet2019** [HatemHosam/RT-ViT-Real-time-vision-transformer#1]
In the paper, you mention that the original images and depth maps, initially sized at 640x480, were resized to 448x448 to expedite the training process. Could you please tell me whether this resizing process involves only changing the dimensions of the images and depth maps, or does it also include scaling the depth values accordingly? Additionally, could you specify if any interpolation methods were preferred during the resizing for preserving the integrity of the depth information?

**Comment by HatemHosam** [comment]
Yes, the resizing process involves only changing the size of the image and the depth map from 640x480 to 448x448. The interpolation method is the default in OpenCV which is 'bilinear'.

**Comment by hamlet2019** [comment]
Thank you so much for your reply🙇
